networks:
  laravel-network:
    external: true
services:
  laravel-app:
    build:
      args:
        uid: ${UID}
      context: .
    container_name: laravel-app
    environment:
    - APACHE_RUN_USER=#${UID}
    - APACHE_RUN_GROUP=#${UID}
    networks:
    - laravel-network
    ports:
    - ${HOST_PORT}:80
    volumes:
    - .:/var/www/html
  mysql-db:
    container_name: mysql-db
    environment:
    - MYSQL_ROOT_PASSWORD=root_pass
    - MYSQL_PORT=${DB_PORT}
    - MYSQL_DATABASE=${DB_DATABASE}
    - MYSQL_USER=${DB_USERNAME}
    - MYSQL_PASSWORD=${DB_PASSWORD}
    image: mysql:5.6
    networks:
    - laravel-network
    ports:
    - 3306:3306
    volumes:
    - ./data:/docker-entrypoint-initdb.d
    - db:/var/lib/mysql
version: '3.5'
volumes:
  db:
    driver: local
